// This file is part of KDDockWidgets.
//
// SPDX-FileCopyrightText: 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
//
// SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
//
// Contact KDAB at <info@kdab.com> for commercial licensing options.

// Entry point for consumers importing this as a Slint library, e.g.:
//
//   import { DropArea, GroupData } from "@kddockwidgets";
//
// See app/build.rs for how "@kddockwidgets" gets mapped to this file.

export { DockWidgetData, GroupData, SeparatorData } from "types.slint";
export { TitleBar } from "titlebar.slint";
export { DockWidget } from "dockwidget.slint";
export { Group } from "group.slint";
export { Separator } from "separator.slint";
export { DropArea } from "droparea.slint";
