# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

# Runs with ASAN/UBSAN on macOS, ASAN on Windows
# Linux already covered with qt6-asan.yml (which uses Qt asan as well)

name: ASAN/UBSAN Qt6 (Windows / macOS)

on:
  push:
    branches:
      - main
      - 2.2
  pull_request:
    branches:
      - main
      - 2.2
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - windows-latest
      - macos-15
    strategy:
      fail-fast: true
      matrix:
        preset:
          - name: ci-dev-asan-qt6

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          cache: true

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake -S . -B ./build-${{ matrix.preset.name }} --preset ${{ matrix.preset.name }}

      - name: Build Project ${{ matrix.preset.build_preset_arg }}
        run: cmake --build ./build-${{ matrix.preset.name }}

      - name: Run tests
        run: ctest --test-dir ./build-${{ matrix.preset.name }} --output-on-failure
        env:
          QT_QPA_PLATFORM: offscreen
          QT_QUICK_BACKEND: software
          LSAN_OPTIONS: detect_leaks=0
