# SPDX-FileCopyrightText: 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

# Tests that building KDDW as a QML module works

name: QML module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[only-') || contains(github.event.head_commit.message, '[only-qml-module]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
        preset:
          - ci-qtquick-module-qt6
          - ci-static-qtquick-module-qt6

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.*
          cache: true

      - name: Install spdlog on Ubuntu
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt install libspdlog-dev mold -y

      - name: Install ninja (Windows / Linux)
        if: ${{ runner.os != 'macOS' }}
        uses: turtlesec-no/get-ninja@main

      - name: Install ninja (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install ninja

      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure project
        run: cmake -S . -B ./build --preset ${{ matrix.preset }}

      - name: Build Project
        run: cmake --build ./build

      - name: qmllint
        run: ninja -C ./build all_qmllint

      - name: Run tests on Linux
        run: ctest --test-dir ./build --verbose -j 4
        env:
          QT_QUICK_BACKEND: software
