# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: Qt6 ASAN

on:
  push:
    branches:
      - main
      - 2.4
  pull_request:
    branches:
      - main
      - 2.4
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
        qt-flavor:
          - asan_ubsan

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install spdlog
        run: |
          sudo apt install lld libspdlog-dev ninja-build -y

      - name: Setup Sanitized Qt
        uses: KDABLabs/sanitized-qt-action@v1
        with:
          qt-tag: "v6.11.0-beta2"
          qt-flavor: "${{ matrix.qt-flavor }}"

      # kddw asan build already has ubsan, while Qt has dedicated
      - name: Configure project
        run: cmake -S . -B ./build-dev-asan6 --preset dev-asan6

      - name: Build Project
        run: cmake --build ./build-dev-asan6 ${{ matrix.preset.build_preset_arg }}

      - name: Run tests
        run: ctest --test-dir ./build-dev-asan6 --verbose -j 4
        env:
          QT_QUICK_BACKEND: software
