# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: Valgrind qtwidgets_leak_test

on:
  push:
    paths-ignore:
      # These are built by another workflow
      - src/flutter/**
      - tests/flutter/**
      - examples/flutter/**
      - tests/reference-images/**
      - .github/workflows/create_release.yml
    branches:
      - main
      - 2.2
  pull_request:
    branches:
      - main
      - 2.2

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
    steps:

      - name: Export IS_SELFHOSTED
        run: echo "IS_SELFHOSTED=$IS_SELFHOSTED" >> $GITHUB_ENV

      - name: Install Qt 6.6.0
        uses: jurplel/install-qt-action@v4
        if: env.IS_SELFHOSTED != 1
        with:
          version: 6.6.0
          cache: true

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install lld ninja-build libspdlog-dev valgrind -y

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset=dev6 -DKDDockWidgets_EXAMPLES=OFF

      - name: Build
        run: cmake --build build-dev6 --parallel

      - name: Run valgrind
        run: valgrind --leak-check=full --show-leak-kinds=all --gen-suppressions=all --error-exitcode=1 --exit-on-first-error=yes --suppressions=./valgrind.sup ./build-dev6/bin/qtwidgets_leak_test -platform offscreen
